name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci

      - name: Build
        run: |
          npm run build
          git config --global user.name "Build Agent"
          git config --global user.email rmg.build.agent@users.noreply.github.com
          echo "RMG_VERSION=$(npm version patch -m 'Build RMG version %s')" >> $GITHUB_ENV
          git push && git push --tags

      - name: Upload Artifacts
        run: |
          git clone --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/uat-rail-map-generator.git
          cp -r build/ uat-rail-map-generator/$RMG_VERSION/
          cd uat-rail-map-generator/
          git add .
          git commit -m "Build RMG version $RMG_VERSION"
          git push
