name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 12.14.1
    
    - name: Install Requirements
      run: npm ci

    - name: Build
      run: npx webpack

    - name: Add Artifacts
      run: |
        git checkout -b gh-pages
        git add ./dist/*.* -f
        git config user.email "${{secrets.GIT_EMAIL}}"
        git config user.name "wongchito"
        git commit -m "Deploy to gh-pages from $GITHUB_SHA"

    - name: Publish
      run: |
        git remote rm origin
        git remote add origin https://wongchito:${{secrets.ACCESS_TOKEN}}@github.com/wongchito/RailMapGenerator.git
        git push -fq origin gh-pages
