name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      environment:
        description: Environment (UAT/PRD)
        default: UAT
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      UAT_REPO_NAME: uat-rail-map-generator
      PRD_REPO_NAME: RailMapGenerator

    steps:
      - name: Configure Git
        run: |
          git clone --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/${{ env.UAT_REPO_NAME }}.git
          git config --global user.name "Release Agent"
          git config --global user.email rmg.release.agent@users.noreply.github.com

      - name: Release to UAT
        if: ${{ github.event.inputs.environment == 'UAT' }}
        run: |
          cd ${{ env.UAT_REPO_NAME }}/
          rm -r docs/
          cp -r ${{ github.event.inputs.version }}/UAT/ docs/
          git add .
          git commit -m "Release RMG version ${{ github.event.inputs.version }} to UAT"
          git push

      - name: Release to PRD on GitHub Pages
        if: ${{ github.event.inputs.environment == 'PRD' }}
        run: |
          cd ${{ env.UAT_REPO_NAME }}/
          git clone --single-branch --branch gh-pages --depth 1 https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/wongchito/${{ env.PRD_REPO_NAME }}.git
          cd ${{ env.PRD_REPO_NAME }}/
          rm -r *
          cd ..
          cp -r ${{ github.event.inputs.version }}/PRD/* ${{ env.PRD_REPO_NAME }}/
          cd ${{ env.PRD_REPO_NAME }}/
          git add .
          git commit -m "Release RMG version ${{ github.event.inputs.version }} to PRD"
          git push

      - name: Release to PRD on GitLab Pages
        if: ${{ github.event.inputs.environment == 'PRD' }}
        run: |
          cd ${{ env.UAT_REPO_NAME }}/
          rm -r ${{ env.PRD_REPO_NAME }}/
          git clone --depth 1 https://chitowong:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/chitowong/RailMapGenerator.git
          cd ${{ env.PRD_REPO_NAME }}/
          rm -r *
          cd ..
          cp -r ${{ github.event.inputs.version }}/PRD/ ${{ env.PRD_REPO_NAME }}/
          cd ${{ env.PRD_REPO_NAME }}/
          echo "image: node:12.12.0\npages:\n\tstage: deploy\n\tscript:\n\t\t- mv PRD public\n\tartifacts:\n\t\tpaths:\n\t\t\t- public\n\tonly:\n\t\t- master" > .gitlab-ci.yml
          git add .
          git commit -m "Release RMG version ${{ github.event.inputs.version }} to PRD"
          git push